# Generated by Django 5.2.2 on 2025-06-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0002_category_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["pk"], "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["pk"], "verbose_name_plural": "Товары"},
        ),
    ]
