# Generated by Django 5.2.2 on 2025-06-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="persons.person",
                    ),
                ),
                ("expirience", models.IntegerField(default=0)),
                ("job_title", models.CharField(max_length=200)),
            ],
            bases=("persons.person",),
        ),
    ]
