# Generated by Django 5.0.6 on 2024-06-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("id",)},
        ),
    ]
