# Generated by Django 5.0.7 on 2024-08-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
