# Generated by Django 5.0.7 on 2024-08-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0005_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
