# Generated by Django 5.2.2 on 2025-06-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shop_app.category', verbose_name='Категория'),
        ),
    ]
