# Generated by Django 5.2 on 2025-04-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_agerating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="age_rating",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movies",
                to="movies.agerating",
            ),
        ),
    ]
