# Generated by Django 5.2 on 2025-04-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, db_default="", default="", max_length=100
                    ),
                ),
                ("bio", models.TextField(blank=True, db_default="", default="")),
                (
                    "family_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Single"),
                            ("R", "In A Relationship"),
                            ("M", "Married"),
                            ("D", "Divorced"),
                            ("W", "Widowed"),
                        ],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
