# Generated by Django 5.0.7 on 2024-08-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0007_product_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
