# Generated by Django 5.2.2 on 2025-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0004_product_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Заказы",
                "ordering": ["pk"],
            },
        ),
    ]
