# Generated by Django 5.2.2 on 2025-06-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0006_order_created_at_order_products_order_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, verbose_name="Количество товара"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена товара"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_products",
                        to="shop_app.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_products",
                        to="shop_app.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Товары в заказах",
                "ordering": ["pk"],
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",

        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders",
                through="shop_app.OrderProduct",
                to="shop_app.product",
                verbose_name="Товары заказа",
            )
        ),
    ]
