# Generated by Django 5.0.7 on 2024-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0006_remove_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="shop_app.category"
            ),
        ),
    ]
