# Generated by Django 5.2.4 on 2025-07-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_foodmaster',
            field=models.BooleanField(default=False),
        ),
    ]
