# Generated by Django 5.1.5 on 2025-01-23 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published"]},
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-published"], name="blog_post_publish_493ec4_idx"
            ),
        ),
    ]
